# This is a basic workflow to help you get started with Actions

name: Compiling Action

# Controls when the workflow will run
# on: push
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout Repository
        uses: actions/checkout@v2

      # Setting up JDK 11
      - name: Step 2 - Setting up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      # Package Program Using Maven
      - name: Step 3 - Package Project using Maven
        run: mvn -B package --file pom.xml
        
      # List everything of the current directory
      - name: Step 4 - List the current directory
        run: ls -a
        
      # Target folder completion
      - name: Step 4 - List items in target folder
        run: |
          cd target
          ls -a
          
      # Target folder completion
      - name: Step 5 - Copying Files for download          
        uses: actions/upload-artifact@v2
        with:
          name: Published Jar Files
          path: target/*.jar
